version: "3.10"

services:
  database:
    image: postgres:15
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
  task_manager:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: task-manager
    depends_on:
      - database
    ports:
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    command: >
      sh -c "poetry run python manage.py migrate && poetry run gunicorn -w 5 -b 0.0.0.0:8000 task_manager.wsgi"


volumes:
  postgres_data:
